services:
  python-app:
    build: .
    ports:
      # user can override host port mapping, defaults to 8000
      - "${PORT:-8000}:8000"
    environment:
      - OBSERVABILITY_BACKEND=${OBSERVABILITY_BACKEND:-signoz}
