server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: ""

scrape_configs:
  - job_name: python_app_logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: python_app_logs
        __path__: /var/log/app.log
    pipeline_stages:
    - match:
        selector: '{job="python_app_logs"}'
        stages:
        - json:
            expressions:
              level: level
              message: event
              timestamp: timestamp
              path: path
              method: method
              process_time: process_time
              status_code: status_code
        - labels:
            level:
        - output:
            source: message